learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
'''定义learning_logs的URL模式'''

from django.conf.urls import url
from . import views

urlpatterns = [

    # 主页
    url(r'^$', views.index, name='index'),
    # 显示所有的主题
    url(r'^topics/$', views.get_all_topics, name='topics'),
    # 显示主题内容
    url(r'^topic/(?P<topic_id>\d+)/$', views.get_topic_entries, name='topic'),
    # 添加主题页面
    url(r'^new_topic/$', views.add_topic, name='new_topic'),
    # Ajax查询主题下是否有条目
    url(r'^ajax_verify_is_empty_of_topic/$', views.is_empty_topic, name='query_topic'),
    # Ajax请求删除主题
    url(r'^ajax_req_del_topic/$', views.del_topic, name='del_topic'),
    # 在某主题下添加一条记录
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.add_entry, name='new_entry'),
    # 编辑某条记录
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    # 删除某条记录
    url(r'^del_entry/$', views.del_entry, name='del_entry'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    #登录页面
    url(r'^login/$', login, {'template_name':'users/login.html'}, name='login'),
    #注销页面
    url(r'^logout/$', views.logout_view, name='logout'),
    #注册页面
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符表示"""
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic
from .models import Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'color': 120})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from .models import Topic
from .models import Entry
from .forms import TopicForm
from .forms import EntryForm
from django.contrib.auth.views import login_required
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template
import json


def index(request):
    """学习笔记主页"""
    return render(request, 'learning_logs/index.html')


@login_required
def get_all_topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def get_topic_entries(request, topic_id):
    """显示单个主题的所有列表"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求主题属于当前用户
    if request.user != topic.owner:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def add_topic(request):
    """创建新的主题"""
    if request.method != 'POST':
        # 未提交数据，创建一个新表单
        form = TopicForm()
    else:
        # Post提交的数据，对数据进行处理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@csrf_exempt
@login_required
def is_empty_topic(request):
    """查询topic下是否有条目"""
    if not request.user.is_authenticated():
        return Http404
    if request.is_ajax():
        # print(request.POST.get('topic_id'))
        topic_id = json.loads(request.POST.get('topic_id'))
        topic = Topic.objects.get(id=topic_id)
        entries = topic.entry_set.all()
        if len(entries) != 0:
            return HttpResponse(json.dumps({'result': 'NoEmpty'}))
        else:
            return HttpResponse(json.dumps({'result': 'Empty'}))


@csrf_exempt
@login_required
def del_topic(request):
    """删除一条主题"""
    if not request.user.is_authenticated:
        return Http404
    if request.is_ajax():
        topic_id = json.loads(request.POST.get('topic_id'))
        Topic.objects.filter(id=topic_id).delete()
        topics = Topic.objects.filter(owner=request.user).all()
        template = get_template('learning_logs/t_topic.html')
        html = template.render({'topics': topics})
        return HttpResponse(json.dumps({'result': 'succeed', 'html': html}))


@login_required
def add_entry(request, topic_id):
    """创建新纪录"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑既定条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 确保编辑的条目属于当前登陆的用户
    if request.user != topic.owner:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
@csrf_exempt
def del_entry(request):
    """删除既定条目"""
    if not request.user.is_authenticated():
        return Http404
    if request.is_ajax():
        entry_id = json.loads(request.POST.get('entry_id'))
        topic = Entry.objects.get(id=entry_id).topic
        Entry.objects.filter(id=entry_id).delete()
        entries = topic.entry_set.order_by('-date_added')
        template = get_template('learning_logs/entry.html')
        html = template.render({'get_topic_entries': topic, 'entries': entries})
        return HttpResponse(json.dumps({'result': 'succeed', 'html': html}))

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import logout, login
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    '''注销用户'''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    '''用户注册'''
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            auth_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, auth_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>印象笔记</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
  <!--static navbar-->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" datd-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'learning_logs:topics' %}">topics</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>Hello, {{user.username}}.</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">Register</a></li>
            <li><a href="{% url 'users:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </div><!--/.container-->
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">返回 {{topic}}</a></p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">保存</button>
  {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/entry.html
{% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>
          <small><span>时间:&nbsp&nbsp</span></small>{{ entry.date_added|date:'M d,Y H:i' }}
          <small>
            <span style="float: right;padding-left: 10px;"><a href="javascript:$.show_modal()">删除</a></span>
            <input type="hidden" id="entry_id" value="{{ entry.id }}">
            <input type="hidden" id="entry" value="{{ entry }}">
            <span style="float: right;padding-right: 10px;"><a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑</a></span>
          </small>
        </h4>

      </div>
      <div class="panel-body">
        <h4>{{ entry.text|linebreaks }}</h4>
      </div>
    </div>

    {% empty %}
    <p>还没有添加任何主题。</p>
{% endfor %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <div class="jumbotron">
    <h1>记录您的学习的收获。。。</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">注册</a> 一个账户来开始您的学习之旅吧！
  </h2>
  <h2>
    whatever your learn something new about a topic, make an entry summarizing what you're learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">返回 {{topic}}</a></p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">添加笔记</button>
  {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
  <h2>添加新的条目</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">添加主题</button>
  {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/t_topic.html
{% for topic in topics %}
    <li>
      <h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        <small>
          <a href="javascript:$.del_topic({{ topic.id }})" style="float: right">删除</a>
        </small>
      </h3>
    </li>
{% empty %}
    <p>目前还没添加任何主题。</p>
{% endfor %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}{% block header %}  <h2>{{ topic }}</h2>{% endblock header %}{% block content %}  <p><a href="{% url 'learning_logs:new_entry' topic.id %}">添加笔记</a></p>  <div id="entry_list">    {% include 'learning_logs/entry.html' %}  </div>  <!--模态对话框-->  <div class="modal fade" id="modal" tabindex="-1" role="dialog">    <div class="modal-dialog" role="document">      <div class="modal-content">        <div class="modal-header">          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="True">&times;</span></button>          <h4 class="modal-title">您确定要删除这条记录吗？</h4>        </div>        <div class="modal-body">        </div>        <div class="modal-footer">          <a class="btn btn-default" data-dismiss="modal">Close</a>          <a class="btn btn-primary" href="#" id="modal_del_btn">Delete</a>        </div>      </div>    </div>  </div>  <!--模态对话框结束-->  <script type="text/javascript" charset="utf-8">    $.show_modal = function () {      <!--获取input传递的值-->      entry_id = $("#entry_id").attr("value");      entry = $("#entry").attr("value");      <!--动态初始化模态对话框-->      $("#modal .modal-body").html("<h4>" + entry + "</h4>");      $("#modal_del_btn").attr("href", "javascript:$.del_req(" + entry_id + ")");      <!--初始化完成后将其显示出来-->      $("#modal").modal("show");    };    $.del_req = function (entry_id) {        $("#modal").modal("hide");        $.ajax({            type:'post',            url:{% url 'learning_logs:del_entry' %},            data:{'entry_id': entry_id},            dataType:'json',            timeout:10000,            async:false,            success:function (resp) {                if(resp.result == "succeed"){                    $("#entry_list").html(resp.html);                }else{                    alert("Failed to delete entry!");                }            }        });    };  </script>{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>主题</h2>
{% endblock header %}

{% block content %}
<ul id="topic_list">
{% include 'learning_logs/t_topic.html' %}
</ul>
<h4><a class="btn btn-primary" style="margin-top: 30px;" href="{% url 'learning_logs:new_topic' %}">添加新的主题</a></h4>

<script type="text/javascript" charset="utf-8">
  $.del_topic = function (topic_id) {
      $.ajax({
        type:'post',
        url:{% url 'learning_logs:query_topic' %},
        data:{'topic_id': topic_id},
        dataType:'json',
        timeout:10000,
        async:false,
        success:function (resp) {
            if(resp.result == "NoEmpty"){
                alert("该主题下面还有记录！");
            }else{
                del_topic(topic_id);
            }
        }
      });
  };

  function del_topic(topic_id) {
    $.ajax({
        type:'post',
        url:{% url 'learning_logs:del_topic' %},
        data:{'topic_id': topic_id},
        dataType:'json',
        timeout:10000,
        cache:false,
        success:function (resp) {
            console.log(resp.html);
            console.log(resp.html);
            if(resp.result == "succeed"){
                $('#topic_list').html(resp.html);
            }else{
                alert("主题删除失败！")
            }
        }
    })
  }
</script>
{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
  <h1>Login to you account</h1>
{% endblock header %}
{% block content %}

<form class="form" action="{% url 'users:login' %}" method="post">
  {% csrf_token %}
{#  {{form.as_p}}#}
  {% bootstrap_form form %}
  {% buttons %}
    <button class="btn btn-primary" name="submit">Login</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{%endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Register</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'users:register' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Register</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}